server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUri:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    score-service: /score/**