server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/ylong/workspace/IntelliJProjects/msproject/confserver/src/main/resources/config/licensingservice
        git:
          uri: https://gitlabe1.ext.net.nokia.com/ylong/config-repo
          searchPaths: licensingservice, organizationservice
          username: ylong
          password: $Leo1234*