example.property: "I AM DEV"
spring.jpa.database: "MYSQL"
spring.datasource.platform: "org.hibernate.dialect.MySQL55Dialect"
spring.jpa.show_sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/msproject?useUnicode=yes&characterEncoding=UTF-8"
spring.datasource.username: "msproject"
spring.datasource.password: "msproject"
spring.datasource.testWhileIdle: "true"
spring.jpa.hibernate.ddl-auto: "update"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL55Dialect"