server:
  port: 8889
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/ylong/workspace/IntelliJProjects/msproject/confserver/src/main/resources/config/licensingservice
        git:
          uri: https://github.com/longyg/config-repo
          searchPaths: licensingservice, organizationservice
          username: longyg
          password: long290686