server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: refresh, hystrix.stream
  endpoint:
    health:
      show-details: always

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user
    client:
      clientId: msclient
      clientSecret: msclient
      scope: all
      grantType: password
      accessTokenUri: http://localhost:8901/oauth/access_token
      userAuthorizationUri: http://localhost:8901/oauth/authorize

logging:
  level:
    org.springframework: INFO