server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: refresh, hystrix.stream
  endpoint:
    health:
      show-details: always

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user

logging:
  level:
    org.springframework: DEBUG